---
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
        exclude: (migrations/|metadata/)

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.9
    hooks:
      - id: helmlint # https://github.com/gruntwork-io/pre-commit#helm-lint-caveats


-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace